### PR TITLE
Fix flandreas/antares#715

### LINKED ISSUE #715: RAM can ignore writes.
This was the hardest to find so far with hours and hours of debugging my circuit because I thought the error was there, but I really want to believe in Antares so here goes:

- create an unclocked RAM with data and address width 12
- write value 2055 to address 2055
- write value 0 to address 2055
- the content is still 2055

Using other values than 0 always works and using most other addresses work with 0, that's what made this so hard to blame on Antares rather than my simulated CPU circuit.

Video 1 shows my experimental setup with a successful write of 1, video 2 shows how the same experiment leads to a discarded write if the value is 0.

https://github.com/flandreas/antares/assets/5798899/907418fb-5179-4eac-a618-6335c8b2c299

https://github.com/flandreas/antares/assets/5798899/21a4934d-c375-41de-95fe-686e708c79e6

### PR DESCRIPTION
**Pull request by fpw**
This should fix flandreas/antares#715.

The optimization that discards a zero write if no segment has been created so far used an invalid calculation of the segment address, leading to invalid optimizations.

### CODE REVIEW

**Comment by fpw** [comment]
PS: I'm not entirely sure that `getSegment` is correct. I chose to change `hasSegment` because the rest seemed to work, but now that my mind is becoming clear again, I don't understand the logic in `getSegment`. Doesn't the divide followed by multiply basically do `floor(address / segmentSize) * segmentSize` so that address 0 .. 255 are mapped to segment 0 (correct) while 256 is already mapped to segment 256 instead of 1 (incorrect)?

This still works because every access undergoes this mapping, but I don't understand why it's not just `[address / size][address % size]`, i.e. why `getSegment` multiplies with `segmentSize` again. It either wastes mapping indices or I don't understand it.

**Comment by fpw** [comment]
Ah, got it: The constructor of `Segment` wants the _base address_, but it was also used as a _segment index_. I now changed the code to actually fix this instead of touching `hasSegment`.

**Comment by flandreas** [comment]
Glad that you found this, and thanks for fixing it right away.
I'll try to change the base branch to release-1.11, from where we probably will release a 1.11.1 bugfix release. The master is targeted for 1.12 with the upcoming Antares Web features, and that might still take a while. I'll then propagate the PR commits to master.

**Comment by flandreas** [comment]
OK, head of your PR is too much ahead of head of release-1.11. I will merge into master and then probably cherry-pick it into release-1.11.

**Pull request merged**
