### PR TITLE
Use plain text for keyboard view

### PR DESCRIPTION
**Pull request by fpw**
This addresses flandreas/antares#725:

* since RichText seems to be used for everything, I didn't find a `Drawable` that simply displays text
* instead, I added a `richText` boolean property to `Label`, allowing to use a label where rich text is not desired
* if rich text is not desired, the new `RichText.asPlain` method is used to construct a `RichText` object from an unparsed text

One thing I couldn't solve: If the `richText` property is set to false, the initial text is still parsed because `text` is initialized first and uses the default value of `richText` which is true. I don't know how to fix this without changing the initialization order.

Finally, this doesn't solve the other issue mentioned in the ticket where space and enter on the keyboard also trigger the respective hotkey actions, e.g. pausing the simulation.

### CODE REVIEW

**Comment by flandreas** [comment]
I see the problem. Maybe `KeyboardView` shouldn't use `Label`, but instead directly draw the text using `Graphics2D.drawString()`. This would work around the issues with (anyway not needed) rich text capabilities, but would pose additional challenges of vertical positioning and maybe also mirroring.

This raises a design issue: `Label` combines the two aspects "Rich text rendering" and "Text alignment", but we want to vary them separately: Alignment, but no rich text. One solution could be to introduce an abstract `TextDrawable` and use this abstraction in `Label`, which sees it just as a rectangular box with text and font. And then implement a "SimpleTextDrawable' given to `Label` by `KeyboardView`.

But that would be a larger change, and you need a solution for your keyboard application sooner. I'll check out the initialisation sequence problem and revert back to you.

The issue the hotkey actions asks for a general solution. Focusable components should be able to overwrite the JVM component's `KeyBindings`. I would extract this into a separate issue. I don't have a solution yet, will probably be somewhere in the area of `FocusManager` and `CanvasJvm`.

**Comment by flandreas** [comment]
In order to make the following test in `LabelTest` pass

```
@Test
    fun shouldConstructWithFormattedPlainText() {
        val label = Label(
            text = "!",
            font = FontImpl(LogicalFontFamily.MONOSPACED, FontStyle.PLAIN.value, 10),
            richText = false)
        assertEquals("!", label.text)
    }
```

you could pass `richText` before `displayableText` in the constructor of `Label`:

```
class Label(
	text: String?,
	font: Font,
	var color: Color? = null,
	horizontalAlignment: HorizontalAlignment = DEFAULT_HORIZONTAL_ALIGNMENT,
	verticalAlignment: VerticalAlignment = DEFAULT_VERTICAL_ALIGNMENT,
	location: Point2D = Point2D.ZERO,
	rotationDisplayStrategy: RotationDisplayStrategy = RotationDisplayStrategy.IGNORE,
	val rotation: Rotation = Rotation.R0,
	ownerRotation: Rotation = Rotation.R0,
	val richText: Boolean = true,
	displayableText: RichTextDrawable = if (richText) RichTextDrawable.of(text ?: "", font) else RichTextDrawable.asPlain(text ?: "", font)
)
```

Not the most beautiful solution, but it should work.

**Comment by fpw** [comment]
Thanks, that worked. I thought that the setter if `text` was being invoked, it also parses it as RichText. But I guess that setter is only called if there's an external set after the constructor has run. 

Committed and pushed the improvement.

**Review by flandreas — APPROVED** [review]

**Comment by flandreas** [comment]
Implemented hotkey issue with #727

**Pull request merged**
