### PR TITLE
#730: Edge-triggered RAM writes

### PR DESCRIPTION
**Pull request by fpw**
This PR addresses flandreas/antares#730. I believe the previous behavior would be impossible to implement in real hardware, so this makes it more realistic - and matches the distributed RAM in all FPGAs I've encountered. Example from Xilinx ([source](https://webpages.uidaho.edu/~jfrenzel/440/Handouts/Memory/Distributed%20Memory/Distributed%20Memory%20Example.pdf)):

grafik

Here, an additional WCLK is introduced to make WRITE_EN edge-triggered. But that's only an implementation detail because FPGAs should never use non-clock signals for edge triggering, but the principle stays the same: Writing must be edge-driven.

But still, this is a suggested change in behavior rather than a bugfix.

### CODE REVIEW

**Comment by flandreas** [comment]
I still don't get how this is different from synchronous RAM.

Without WCLK, your circuit would have to generate a correctly timed WRITE_EN signal if WRITE_EN was supposed to be edge-triggered. And this would just be CLK in a synchronous RAM if WRITE_EN is set to 1.

To me, it looks like you want a clocked circuit without a clock. Is this the way the PDP-8 is constructed, and you want to get as close as possible to the original design?

**Comment by fpw** [comment]
I also saw that LogiSim has the same behavior, but some people also reported this as counter intuitive. One of the successor projects solved this the same way: https://github.com/logisim-evolution/logisim-evolution/issues/312 (referring to their issue 119)

> ... hence the read-port will have the same behavior as an asynchronous RAM, whilst the write port only writes on rising/falling edge

But I understand the compatibility with Logisim is important, so I'll just add a pulse generator to my write input.

**Comment by flandreas** [comment]
@fpw Sorry Folke, maybe we should reopen this one.

Compatibility with Logisim is not important. It's just that I didn't understand the requirement properly. I wasn't aware that the field distinguishes between read and write synchronous/asynchronous behaviour. You seem to be more the expert in these things than I am.

I was also concerned about backward compatibility, as this change would possibly break some projects out there. Is there a way we can make this new behaviour backward compatible? Or do you think this is not necessary because most or all useful applications would want it anyway in the new behaviour?

**Comment by fpw** [comment]
It's rather easy as a user to get the desired behavior by adding an external register to the address input in the circuit, so the current Antares interpretation is more flexible as it allows both edge- and level-triggered designs.

However, I believe that there is simply no real-world use for the level-triggered write as it would be impossible to implement changing the address while write is active in real hardware. In your latch analogy, imagine a demultiplexer that selects the latch based on the address - when the address changes, the multiplexer doesn't update all its outputs at the same time, so it takes a few ns until the proper latch is selected, maybe activating different demultiplexer outputs in between. And while the output changes, the write would be "smeared" across all these locations. So having this level-triggered ability allows to create circuits in Antares (and Logisim) that would not work in the real world. This is also possible to see in Antares when the noise feature is used.

A backward-compatible way would probably be to just make the trigger type a property of the RAM with the default being false. But the users that figure out that they need to make it edge-sensitive could also simply add registers themselves. My main point was that the default intuition of a hardware / FPGA designer would be the expectation that write is edge-triggered by default.

But since the other tools offer a different default, maybe my intuition is just wrong or biased because I mostly work with real (FPGA) circuits nowadays. I think that in the end, this is a question of perspective.

I think that only very few people would be affected by this because most designs are synchronous nowadays, and asynchronous writers probably don't change the address while the write is active. I can also perfectly live with the current implementation now that I know about this behavior.

**Comment by flandreas** [comment]
You've convinced me. Your PR would make Antares better. I'd appreciate if you would reopen the PR, and I'll merge it.

I think the WR pin should then have an edge-triggered annotation. If you like, you could try to adjust that, or I could do it after the merge.

**Comment by fpw** [comment]
> I think the WR pin should then have an edge-triggered annotation.

That was already part of the PR :-) Toggling whether the RAM has a clock also toggles the edge symbol in the GUI.

> I'd appreciate if you would reopen the PR, and I'll merge it.

Great, I'll try to make the behavior a new property of the RAM, I believe that's the best compromise. Will reopen once I'm done with that.

**Pull request closed without merging**
